### ISSUE TITLE
The version of `svelte-preprocess` in the template has a deprecated dependency

### ISSUE THREAD

**Issue by BLucky-gh** [ottomated/create-o7-app#10]
`svelte-preprocess`@5.0.1 has a dependency on `@types/sass` which is deprecated, version 5.0.2 fixes this, and the latest version is 5.0.3

I am aware that the version rule `^5.0.1` is supposed to resolve to `5.0.3`, but (at least with `pnpm`) when letting `pnpm create o7-app` do `pnpm install`, it still installs `5.0.1`

**Comment by ottomated** [comment]
Should be fixed in 0.2.0
