### ISSUE TITLE
Suggestion: Use inquire's set_global_render_config method

### ISSUE THREAD

**Issue by mikaelmello** [ottomated/create-o7-app#15]
Hey, I've been taking a look at some projects that use inquire and I noticed you are passing down the RenderConfig instance all the way to each prompt call.

I've only glanced at the code so I might have misinterpreted it :) But if that's the case, see if the function to set it globally once might be of interest to you.

>  If you do not want to re-set the render config object for each new prompt you create, you can call inquire::set_global_render_config to set a global RenderConfig object to be used as the default one for all future prompts.
>
> https://github.com/mikaelmello/inquire#rendering-configuration-aka-color-themes

**Comment by ottomated** [comment]
Not going to fix what isn't broken :)
