### ISSUE TITLE
Add changelog to GitHub releases

### ISSUE THREAD

**Issue by liamwh** [ottomated/create-o7-app#32]
I'd like to watch the releases on GitHub and be informed of what is changing. Could you please could include a changelog in the release notes?

A potential solution could be to use something like [git-cliff](https://git-cliff.org/) with [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

**Comment by ottomated** [comment]
Will look into this, would have to rewrite the entire repo's commit history to do so unfortunately

**Comment by liamwh** [comment]
Why do you feel you'd need to re-write the repo's commit history?

You can just do it from this point forward right?

**Comment by ottomated** [comment]
Closed by #46
