### ISSUE TITLE
Edge DB template .env - sslaccept

### ISSUE THREAD

**Issue by VICTORVICKIE** [ottomated/create-o7-app#4]
**Hey Otto,**

I've been looking into the project and found out this line, is this intentional? 

The planetscale sslaccept will be `?sslaccept=strict`
https://github.com/ottomated/create-o7-app/blob/3b550dbbba5fd6010cf7dfddb71851fb9fee94c7/template_builder/templates/extras/%7BDatabase%2CEdge%7D.env#L6

If so can i make a PR to change the above.

**Comment by ottomated** [comment]
If you look into it further, you'll see that the DATABASE_URL there is only used for schema generation.
